In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [20]:
data = pd.read_csv('/content/Melbourne_housing_FULL.csv')

In [8]:
data.head(5)

       Suburb             Address  ...             Regionname Propertycount
0  Abbotsford       68 Studley St  ...  Northern Metropolitan        4019.0
1  Abbotsford        85 Turner St  ...  Northern Metropolitan        4019.0
2  Abbotsford     25 Bloomburg St  ...  Northern Metropolitan        4019.0
3  Abbotsford  18/659 Victoria St  ...  Northern Metropolitan        4019.0
4  Abbotsford        5 Charles St  ...  Northern Metropolitan        4019.0

[5 rows x 21 columns]

In [10]:
data.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [11]:
data.shape

(34857, 21)

In [26]:
df =  data [['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount','Distance', 'CouncilArea',
             'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']]
df.head(5)

       Suburb  Rooms Type Method  ...  Car Landsize  BuildingArea      Price
0  Abbotsford      2    h     SS  ...  1.0    126.0           NaN        NaN
1  Abbotsford      2    h      S  ...  1.0    202.0           NaN  1480000.0
2  Abbotsford      2    h      S  ...  0.0    156.0          79.0  1035000.0
3  Abbotsford      3    u     VB  ...  1.0      0.0           NaN        NaN
4  Abbotsford      3    h     SP  ...  0.0    134.0         150.0  1465000.0

[5 rows x 15 columns]

In [28]:
df.shape

(34857, 15)

In [30]:
df.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [31]:
cols_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
df[cols_fill_zero] = df[cols_fill_zero].fillna(0)
df.isnull().sum()

/tmp/ipykernel_1382/1817879498.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols_fill_zero] = df[cols_fill_zero].fillna(0)

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        0
Distance             0
CouncilArea          3
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [34]:
df['Landsize'] = df['Landsize'].fillna(df.Landsize.mean())
df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())
df.isnull().sum()

/tmp/ipykernel_1382/684183548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Landsize'] = df['Landsize'].fillna(df.Landsize.mean())
/tmp/ipykernel_1382/684183548.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
landsize            0
dtype: int64

In [35]:
df.dropna(inplace=True)
df.isnull().sum()

/tmp/ipykernel_1382/3641017954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
landsize         0
dtype: int64

In [42]:
df=pd.get_dummies(df,drop_first=True).astype(int)
df.head()

   Rooms  ...  CouncilArea_Yarra Ranges Shire Council
1      2  ...                                       0
2      2  ...                                       0
4      3  ...                                       0
5      3  ...                                       0
6      4  ...                                       0

[5 rows x 746 columns]

In [43]:
x = df.drop('Price',axis=1)
y = df['Price']

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [45]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [46]:
model.score(x_test,y_test)

0.13413168587604662

In [47]:
model.score(x_train,y_train)

0.6825862950046448

Which is a Overfitting and we use Regularization techiques for this

1. Lasso regression - L1

In [50]:
from sklearn.linear_model import Lasso

In [51]:
lasso = Lasso(alpha = 50,max_iter=100,tol=0.1)
lasso.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.323e+15, tolerance: 7.963e+14
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100, tol=0.1)

In [53]:
lasso.score(x_test,y_test)

0.6633189114259245

In [54]:
lasso.score(x_train,y_train)

0.6765561935632322

In [57]:
print(lasso.coef_)

[ 2.70873379e+05  5.21643825e+00 -2.91053364e+04 -8.48906145e+04
  1.23144631e+05  4.17152260e+04  3.29707173e+00  8.75189549e+01
 -7.27124040e-01  2.22194904e+05 -1.27603593e+05 -0.00000000e+00
  3.38840823e+05  1.48593739e+05  3.01707520e+05  1.29908371e+05
 -1.09880831e+05 -1.29617061e+05 -0.00000000e+00  1.59195237e+05
 -1.01796608e+05 -9.38905242e+03 -0.00000000e+00  2.16878137e+04
 -1.43765285e+05 -0.00000000e+00 -2.79594057e+05  0.00000000e+00
 -3.38618547e+04  2.19056089e+05  5.68141805e+04  2.84797659e+04
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.89158992e+05
 -1.87496453e+05  3.61811590e+04 -1.09157220e+05  4.31767852e+04
  2.57802107e+05  1.89481441e+05 -7.03477773e+02 -0.00000000e+00
  6.95561987e+04  1.45129521e+04  0.00000000e+00  2.51723954e+05
 -1.33117864e+05 -0.00000000e+00  4.91786489e+05 -0.00000000e+00
  3.29723992e+04  0.00000000e+00  1.92737480e+05  4.87036555e+04
  8.04743289e+04  0.00000000e+00  0.00000000e+00 -1.73255103e+05
  0.00000000e+00 -1.86287359e+05 -0.00000000e+00 -0.00000000e+00
 -1.98869829e+04 -4.52433112e+04 -0.00000000e+00 -5.58618756e+04
  1.03351004e+05 -6.30813190e+03  6.00230806e+05  1.84583436e+05
  3.52693460e+05 -2.09318706e+04 -2.44942073e+04  1.70950934e+05
 -1.97014907e+05 -1.41264197e+05  1.81442236e+04  2.96979337e+04
  1.31627424e+04 -7.25099832e+04  2.32559068e+05 -1.36793752e+04
 -2.48641189e+05 -0.00000000e+00 -2.24397238e+05  1.65708127e+05
 -9.92538216e+04  8.04835271e+04  0.00000000e+00 -1.09190027e+05
 -1.88715040e+05 -0.00000000e+00  1.19107010e+04  0.00000000e+00
 -9.32876690e+04 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -1.45081942e+05 -0.00000000e+00
 -1.27641938e+05  0.00000000e+00  0.00000000e+00 -3.28805609e+04
 -0.00000000e+00 -4.20145779e+04 -4.98568560e+04  0.00000000e+00
 -1.43144957e+05 -2.21484127e+05 -0.00000000e+00  3.44539298e+04
  8.32211521e+04 -2.71640357e+05 -0.00000000e+00  4.32298406e+05
  4.09228060e+05  1.18636458e+05  6.58822454e+04 -2.33509726e+04
 -1.83717025e+05  7.09551424e+04  0.00000000e+00 -1.59441893e+05
 -2.51637241e+04  8.83369481e+04  9.55928721e+02 -8.96960790e+03
  0.00000000e+00  0.00000000e+00  1.80835796e+05  4.10099075e+04
  2.05582265e+04  0.00000000e+00  1.70766302e+05  2.92472388e+05
 -2.68857721e+04  0.00000000e+00 -7.46456757e+03  3.45410445e+04
 -2.20491368e+04  2.33964567e+05 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -5.72703065e+03 -3.09467897e+04
  3.26613399e+05 -1.49476226e+05 -1.45708005e+05 -7.86641124e+03
  2.39243745e+04 -1.69856686e+05  0.00000000e+00  2.37143646e+05
 -1.49254345e+05 -0.00000000e+00 -1.67910860e+05 -5.23543879e+04
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -2.47906182e+04
 -2.51105953e+05 -3.69927119e+05 -4.56352401e+04 -3.58978831e+04
  0.00000000e+00  7.56765627e+03 -2.82299113e+04 -0.00000000e+00
  6.64312215e+04  5.01695212e+05 -2.04679582e+04  0.00000000e+00
 -7.66857416e+04  4.09724130e+04 -0.00000000e+00  9.63327720e+04
  0.00000000e+00 -0.00000000e+00 -2.45408242e+04 -0.00000000e+00
 -7.36350054e+04  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -3.81625553e+03  7.94210710e+04 -7.38873556e+03  0.00000000e+00
 -0.00000000e+00 -4.01274391e+04  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  5.51384270e+03 -5.04721221e+04  4.41208024e+05 -3.24863354e+04
  0.00000000e+00  1.17175276e+05 -0.00000000e+00  6.76687332e+04
 -0.00000000e+00  4.87182414e+03 -0.00000000e+00  1.29331188e+05
  0.00000000e+00  0.00000000e+00  6.62796853e+05 -8.65655258e+04
  9.59298245e+04 -0.00000000e+00  2.37514984e+05 -3.06627957e+04
 -0.00000000e+00  6.36649814e+04 -2.54964869e+05 -6.89924063e+04
  1.64488073e+05 -0.00000000e+00  2.59347430e+05  6.10419467e+04
 -1.89975821e+04  0.00000000e+00 -2.72241769e+06  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  1.22159038e+04  0.00000000e+00
  2.13436477e+05  0.00000000e+00  0.00000000e+00  2.39603003e+04
 -2.51917575e+03 -0.00000000e+00 -2.33392670e+05  0.00000000e+00
  5.60046975e+04  0.00000000e+00  2.14390656e+05  3.42875636e+05
 -7.46738383e+04  0.00000000e+00  0.00000000e+00  2.45883400e+04
 -1.15012143e+05 -1.16176404e+05 -2.33729483e+05 -9.63012221e+04
  3.39223920e+05 -0.00000000e+00 -1.54913577e+05 -1.84104027e+04
  0.00000000e+00  4.52973095e+03  4.53827983e+04 -1.19266666e+05
 -0.00000000e+00  0.00000000e+00 -1.20981399e+05 -1.49303947e+05
 -8.67129475e+04 -0.00000000e+00  2.10603247e+05  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  8.64133339e+04
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  1.03951471e+04
 -5.03607348e+04 -1.51925506e+05 -4.02562546e+05  0.00000000e+00
  0.00000000e+00  0.00000000e+00  6.86717878e+04 -1.41329751e+05
 -5.60223164e+04  3.64163890e+04 -9.99493121e+04  3.33994451e+05
  9.89351855e+04 -0.00000000e+00 -9.42568248e+04  2.56094406e+04
  3.92030551e+04 -0.00000000e+00 -0.00000000e+00 -1.42208719e+04
  0.00000000e+00  1.00735038e+05 -1.23566614e+05  0.00000000e+00
  5.63078826e+04  9.53603873e+04  1.48687325e+05  0.00000000e+00
  0.00000000e+00  1.18380545e+05  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -3.07781967e+05  0.00000000e+00  0.00000000e+00
 -1.43797204e+05 -1.12971226e+05  1.71519911e+05 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -9.52947661e+04 -0.00000000e+00
 -8.25424510e+04 -0.00000000e+00 -2.62026136e+04  7.08345369e+04
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  3.50823489e+05  0.00000000e+00 -4.57638987e+04
  5.17758637e+04  0.00000000e+00  2.52783322e+05 -1.32124966e+05
  0.00000000e+00  6.33923674e+04 -0.00000000e+00  0.00000000e+00
 -2.74184931e+05 -4.76457476e+05  6.70478494e+04  2.39421393e+04
  2.88758400e+04  1.41251835e+04 -0.00000000e+00  0.00000000e+00
  6.27167991e+05  0.00000000e+00  0.00000000e+00  0.00000000e+00
  9.69975888e+03 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  3.47628850e+03 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  1.02655379e+05  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -5.60459039e+04
 -3.53854412e+02  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  1.55320889e+04  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -4.72401241e+04 -2.87024056e+03  1.25413362e+04  0.00000000e+00
 -7.12324607e+03  0.00000000e+00  3.94305547e+04  0.00000000e+00
 -0.00000000e+00  1.73007743e+04 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -2.24996120e+03 -0.00000000e+00
  3.55343128e+05  0.00000000e+00  0.00000000e+00  3.04281530e+04
  3.56390948e+05  2.36382618e+04 -0.00000000e+00  8.55952149e+03
 -0.00000000e+00  3.73351613e+04 -0.00000000e+00  5.18652821e+04
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  1.55922806e+05
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -6.64030267e+04 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  8.18975884e+05
  6.64996925e+04 -0.00000000e+00  0.00000000e+00 -7.24069780e+04
  0.00000000e+00 -2.08117207e+04 -2.59285713e+04 -0.00000000e+00
 -3.55369648e+02  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  1.39401515e+03 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -5.07232842e+04 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  2.28826718e+04 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  1.05189140e+06 -4.31267160e+04 -0.00000000e+00  0.00000000e+00
 -1.37392713e+05 -0.00000000e+00 -0.00000000e+00 -2.74734901e+04
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  3.88201479e+05
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  5.04191819e+04  2.61321490e+03  8.46489505e+04
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  4.65097773e+05 -0.00000000e+00  0.00000000e+00  5.17628742e+05
 -0.00000000e+00  0.00000000e+00 -1.49272260e+05 -9.43966923e+03
 -0.00000000e+00  5.17295598e+05 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  1.49085430e+05  3.58529723e+04  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -8.12711674e+04
  0.00000000e+00 -0.00000000e+00 -5.71865380e+04 -0.00000000e+00
  0.00000000e+00  3.00051751e+05 -1.07334037e+05 -0.00000000e+00
  1.56191467e+05  7.18619889e+04  0.00000000e+00  2.87052585e+04
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  2.79029739e+04
 -0.00000000e+00  9.27965879e+04 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.50142305e+05 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.39344907e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  1.39613423e+05 -3.14780680e+04  0.00000000e+00
 -1.35917306e+04 -1.60298631e+05  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -7.39720480e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  1.18433742e+05  7.85508057e+04  2.07906195e+04
 -4.29858546e+04  1.01474323e+04  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -6.38089347e+04
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  2.38847184e+05 -0.00000000e+00 -5.00265513e+03 -0.00000000e+00
 -3.60169219e+04 -0.00000000e+00  0.00000000e+00  5.01814367e+04
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  1.91511338e+04
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -1.58624548e+05
  0.00000000e+00  0.00000000e+00  7.28645716e+04  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -3.89309672e+04
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.29359671e+06  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -4.68483483e+03  0.00000000e+00 -1.58303391e+03
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -8.80342901e+04 -0.00000000e+00
 -6.92566549e+04  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  4.13421524e+04 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -1.22551901e+04  0.00000000e+00 -5.68674088e+01
 -0.00000000e+00  3.03635852e+04  1.28360286e+04 -7.48015930e+04
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -1.45014401e+03 -0.00000000e+00  1.72830990e+04 -4.75781022e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -3.37583056e+04  7.30638005e+04 -1.51418962e+05
  2.78494187e+04  4.73468851e+04  1.86467854e+05 -2.51662083e+05
  0.00000000e+00  2.05688468e+05  2.17744183e+05 -1.53226594e+05
  1.29957865e+05 -0.00000000e+00  3.08671631e+04  2.06096159e+05
  3.81183388e+04 -6.45062076e+04  4.39112033e+04 -2.18624458e+05
  1.57605452e+05 -0.00000000e+00  2.89810642e+05  9.81336261e+04
  1.37739430e+04  3.81363325e+04  9.98987509e+04 -1.80447785e+05
  0.00000000e+00 -5.92829417e+04  2.11152756e+05  0.00000000e+00
  0.00000000e+00 -2.36041297e+03  1.17951913e+03  2.32215036e+05
  5.85779970e+04 -1.36179707e+05 -2.21023066e+05  1.52704747e+05
 -0.00000000e+00]

2. Ridge Regression - L2

In [58]:
from sklearn.linear_model import Ridge

In [59]:
ridge = Ridge(alpha = 50,max_iter=100,tol=0.1)
ridge.fit(x_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [60]:
ridge.score(x_test,y_test)

0.6669747759118905

In [61]:
ridge.score(x_train,y_train)

0.6619849633206998

In [63]:
print(ridge.coef_)

[ 2.74349020e+05  1.42568066e+00 -3.01489988e+04 -8.53891004e+04
  1.30649232e+05  3.79135620e+04  1.50477841e+00  3.50864066e+01
  1.50477550e+00  1.31528675e+05 -6.59159212e+04 -2.01679756e+04
  1.44578362e+05  5.71144601e+04  1.35882804e+05  6.70784733e+04
 -4.65210594e+04 -1.14749651e+05 -1.64497177e+04  9.77926387e+04
 -5.47137405e+04 -3.88698131e+04 -4.61335250e+04  2.31093306e+04
 -3.89796423e+04 -1.61853626e+04 -1.69679171e+05  7.56654569e+03
 -6.52655214e+04  1.40319374e+05  2.89748129e+04  2.73173729e+04
 -1.36581064e+04  1.18920822e+04  5.78157102e+02  7.97072199e+04
 -6.18155409e+04  4.37363234e+04 -7.02613338e+04  4.80496178e+04
  6.84445110e+04  7.09884314e+04 -3.89788904e+04 -2.71550609e+04
  2.58228825e+04  3.35275560e+04  0.00000000e+00  1.16143215e+05
 -7.96424463e+04 -1.12813592e+04  3.74676726e+05 -4.69167595e+04
 -2.03788991e+02  2.47358695e+03  5.35055259e+04  5.76286240e+04
  5.17856438e+04 -7.56230900e+02  0.00000000e+00 -9.93976759e+04
  2.04543210e+04 -1.29727208e+05 -8.63514947e+03 -7.71084799e+03
 -2.89490061e+04 -6.70229143e+04 -2.61467282e+04 -3.76697753e+04
  6.64993248e+04 -2.97459469e+04  3.15796589e+05  7.25563653e+04
  1.68055778e+05 -1.07005162e+04 -3.86284756e+04  6.13236970e+04
 -5.55520174e+04 -4.74819171e+04  1.72829921e+04  3.17227213e+04
  1.75097603e+04 -7.42022678e+04  8.47705935e+04 -1.55576245e+04
 -1.95657905e+05 -3.34840750e+03 -6.54504251e+04  4.23357705e+04
 -4.03857085e+04  3.54671682e+04  1.01955885e+04 -9.87985317e+04
 -1.41783295e+05 -1.84235348e+03 -3.99906437e+03 -5.11000624e+03
 -7.85244172e+04 -1.15900691e+04 -5.87834613e+02 -8.42569832e+03
 -3.94403640e+03 -2.14977205e+04  2.17106527e+04 -1.73354828e+04
 -5.49812733e+03  7.10066721e+03 -7.85410380e+04  6.01176440e+02
 -4.39968004e+04  0.00000000e+00  2.18982647e+03 -3.41711235e+04
 -1.38466261e+04 -3.11522803e+04 -1.22290752e+04  5.37131102e+03
 -5.57784312e+04 -3.38300923e+04  2.66780762e+04  5.86540000e+04
  5.48529138e+04 -7.57816688e+04 -1.80655173e+04  1.51415313e+05
  1.62154162e+05  5.46843729e+04  4.51804062e+04 -2.42048807e+04
 -6.16890521e+04  2.72383648e+03  8.45287310e+03 -4.49744246e+04
 -2.77827224e+04  1.17896879e+05  2.05784920e+04 -8.05509684e+03
  0.00000000e+00  0.00000000e+00  8.23947365e+04 -6.34468645e+03
  4.23130895e+04  0.00000000e+00  9.31997898e+04  1.90945200e+05
 -5.79986424e+04  7.39597552e+02 -3.61674764e+04  6.41459807e+04
 -9.16442138e+03  1.08756483e+05 -1.63647815e+04  6.30869293e+04
  6.80198630e+03 -3.58955725e+04 -1.90655443e+04 -4.22272507e+04
  1.94734213e+05 -1.04228540e+05 -8.69962274e+04 -1.16816966e+04
  6.33603392e+01 -1.01635412e+05  4.00496295e+03  1.36479001e+05
 -1.29725852e+05 -3.80900254e+03 -1.46476584e+05 -6.15973247e+04
  1.40679635e+04 -7.57738230e+03  4.43203562e+03 -3.23738191e+04
 -1.83899078e+05 -2.37718400e+05 -7.20116847e+04 -3.97291179e+04
 -2.78541098e+04 -1.25662415e+04 -2.70692061e+04 -6.45458928e+03
  3.83063000e+04  1.95445856e+05 -4.45512504e+04  3.53369564e+03
 -5.54021090e+04  9.22943418e+03 -2.27071493e+04  3.94357212e+04
  9.50700328e+03 -2.07188024e+04 -6.18798494e+04 -7.82681860e+03
 -7.42356169e+04 -6.12082128e+03  2.47533439e+03 -8.00633569e+03
 -2.23061392e+04  3.51109016e+04 -1.15136013e+04  5.51384920e+03
 -1.08129063e+04 -3.83540089e+04  2.72556221e+04 -1.02105335e+04
 -4.99999678e+03 -1.47098108e+03  2.90128731e+02  1.30463048e+03
  3.46072166e+02 -4.93119242e+04  2.76751459e+05 -3.49595207e+04
 -1.19738127e+04  4.35077916e+04 -1.99823127e+04  5.27475606e+04
 -2.70883922e+04  1.56092777e+03 -1.79574794e+04  8.30785714e+04
 -4.32633008e+03  2.90978123e+03  2.63246011e+05 -6.85571364e+04
  3.42081879e+04 -5.74861689e+02  9.16413769e+04 -2.88841049e+04
 -5.15993023e+03  8.22470032e+04 -1.06605571e+05 -3.23668876e+04
  8.36073396e+04 -9.93643973e+02  1.45016645e+05 -9.97599164e+03
 -2.08110386e+04  7.38036085e+03 -2.29636512e+04 -2.66809419e+04
  2.47381224e+04 -1.79494348e+04 -1.79578603e+04  1.42087289e+04
  1.69091782e+05 -1.97388303e+03  1.16699576e+04  1.42234820e+04
 -3.71731630e+04 -2.67284238e+04 -1.37228156e+05  3.22457704e+03
  3.95630013e+04  2.14478187e+04  1.25161705e+05  1.29554775e+05
 -5.99221807e+04  7.58342466e+03  1.77069563e+04  1.15385611e+04
 -1.03798212e+05 -7.50110051e+04 -1.89680244e+05 -7.49711745e+04
  8.24950348e+04  9.89366355e+02 -9.78810353e+04 -7.13378526e+02
  2.07614314e+04  1.43336963e+04  2.63593528e+04 -4.25497646e+04
 -2.58561792e+04  1.23889383e+04 -9.64583128e+04 -4.45740833e+04
 -8.05454519e+04 -9.65832218e+03  7.60739829e+04  9.98641834e+03
 -1.80408386e+04  2.11251525e+04  2.20280701e+03  4.65346374e+04
  3.69059764e+03 -5.40120033e+03 -2.11424966e+04 -5.11693583e+04
 -4.50512250e+04 -7.04676462e+04 -1.84846811e+05 -2.28404017e+04
 -3.38018045e+03  2.32043465e+02  4.53060050e+04 -3.81252719e+04
 -9.26014665e+04  4.60908646e+04 -2.78449173e+04  2.12200554e+05
  4.33382747e+04 -2.90072695e+04 -9.60412991e+04 -2.20748444e+03
  1.24384581e+04 -3.49691512e+04 -3.11217017e+04 -3.26628574e+04
  0.00000000e+00  7.50396579e+04 -7.60333278e+04  1.88093703e+03
  2.99874110e+04  6.60935057e+04  1.19903268e+05  1.59130787e+04
 -8.92785223e+03  3.17724660e+04  2.44250227e+03  2.82296245e+02
 -1.95981734e+03 -1.76464001e+05  1.55080789e+04  5.48329496e+03
 -5.44291479e+04 -4.42353728e+04  4.31192945e+04 -1.49311845e+04
  1.30793296e+03 -1.68816903e+04 -4.68012562e+04 -4.99026944e+03
 -9.15900177e+04 -8.08450736e+03 -2.83493709e+04  1.26687084e+04
 -2.28772383e+04 -6.19994540e+04  1.02943070e+04  3.17606948e+03
 -5.91910634e+03  2.27039469e+05 -6.96575759e+03 -7.72736769e+04
  1.67417112e+04  4.71801039e+02  9.26991645e+04 -7.10330765e+04
  2.22729572e+03  5.09542445e+04 -7.65286754e+02  1.12141493e+02
 -2.64996639e+05 -4.58771437e+05  6.17363650e+04  1.46011144e+04
  2.24097838e+04  1.66711404e+04 -4.08533464e+03  2.29284292e+02
  1.91579244e+05 -1.56724096e+03  0.00000000e+00  8.72011056e+03
  2.51233331e+03 -3.84317598e+03 -8.50388218e+03 -5.74137799e+03
 -1.72545243e+04  1.31148611e+04  1.10751578e+04 -8.06862913e+03
 -5.29851170e+03 -2.22072878e+03 -7.25556761e+03 -1.00078011e+03
 -3.35070154e+03  9.62637772e+03  4.37327317e+04 -3.92565248e+04
  3.70950475e+03 -7.23086042e+03 -1.01193907e+04 -5.15011918e+04
 -3.04252025e+04  3.62665453e+03 -2.73606257e+03 -2.35537855e+03
  0.00000000e+00 -9.62991725e+03  0.00000000e+00  1.85742936e+03
  1.42520716e+04  0.00000000e+00 -1.24854667e+04 -6.44944357e+03
 -1.75329102e+04 -1.59364818e+04 -8.38705405e+03  3.22395691e+03
 -5.61957983e+04 -2.27155694e+02  1.37675856e+04  0.00000000e+00
 -2.44705218e+03 -6.86889984e+03 -4.70235096e+03  3.77449138e+03
  0.00000000e+00 -7.82772856e+03 -3.35945555e+04 -6.46005134e+03
  1.46844303e+05 -3.58821229e+03  0.00000000e+00  1.42618226e+04
  1.09468208e+05  2.81165833e+04 -7.42921196e+03  2.51831895e+04
 -1.41000573e+04  2.08747659e+04 -1.14117865e+04  3.33773395e+04
 -1.32516690e+04  2.56578163e+03 -1.11462636e+03  1.10686041e+05
  0.00000000e+00  1.71722087e+04  5.82323008e+03  2.67073515e+03
 -4.29463010e+04 -7.33953801e+03  8.74039596e+02 -2.49030776e+03
 -1.31326809e+03 -6.91568973e+03 -5.56843604e+03  4.86333029e+04
  9.52974313e+03 -2.21952715e+03 -8.80375070e+03 -6.32495143e+04
  0.00000000e+00 -1.72995358e+04 -2.56174919e+04 -6.40487175e+03
 -3.32311710e+04 -6.08608535e+03  1.04808485e+04 -1.14523112e+03
 -3.02306649e+03 -1.54577155e+04 -1.92717847e+03 -1.13221964e+04
 -1.66524534e+04 -1.34103106e+04 -3.31127333e+03  0.00000000e+00
  0.00000000e+00 -1.30599584e+04  0.00000000e+00 -1.06921518e+03
 -5.53731381e+03 -7.08000339e+02 -9.01160050e+03 -1.59440875e+04
 -6.77458236e+04 -1.04490012e+04 -6.14873253e+03 -2.86930176e+03
  1.22233584e+04 -6.76858151e+03  8.49417363e+03 -4.08930434e+04
  1.46757860e+05 -2.11166360e+04 -1.87178620e+04 -2.54558882e+04
 -5.66653314e+04 -5.52009495e+04 -4.56157717e+03 -2.45968385e+04
  3.94600062e+03  7.27250756e+03 -5.46500748e+03  2.55382547e+04
  8.93012822e+03 -3.11035631e+03  0.00000000e+00 -6.85966697e+03
 -1.60528255e+04 -5.97099806e+03  6.78026832e+02  2.05075153e+02
  0.00000000e+00  2.70717121e+04  1.14251283e+03  6.83239826e+04
  2.43826437e+03  2.00683326e+02 -1.26580087e+04 -1.01913540e+04
  6.39299984e+03 -3.87775606e+03 -2.82092017e+02 -8.69511489e+03
  3.29272808e+05 -6.06920324e+03  1.90374156e+04  5.09839619e+04
 -4.01767648e+03  1.24396117e+04 -9.70926777e+04 -3.43279161e+04
 -1.11232397e+04  6.61925449e+04 -1.39746760e+04  4.41512290e+03
 -4.95009240e+00  7.40069548e+03  9.40482330e+02  5.23143866e+03
 -6.14882085e+03  5.97924020e+04  7.80894869e+03  0.00000000e+00
 -1.17664199e+04 -3.28713446e+03  5.15934812e+03 -7.30311522e+04
 -1.68952262e+03 -1.14849731e+04 -2.55539215e+04 -3.39988807e+03
  6.72537634e+03  2.78272790e+05 -3.44820416e+04 -2.35959396e+03
  4.03209479e+04  4.02358154e+04  0.00000000e+00  1.27437239e+04
 -3.94860658e+03  0.00000000e+00 -8.67283518e+03  0.00000000e+00
 -1.94352795e+03 -3.18676952e+03  2.66669531e+03  1.20013047e+04
 -3.36587764e+03  4.34465350e+04 -1.57720888e+04  1.28237902e+04
  1.02098135e+04 -3.09769220e+04 -4.00401878e+04 -3.61652512e+04
 -6.15577392e+03  5.90878130e+02 -6.22440004e+03 -3.79538162e+02
 -1.46092988e+03  1.13172135e+04  1.57794980e+04 -5.51132038e+03
 -4.19738857e+03  9.38126814e+04 -4.59897982e+04  0.00000000e+00
 -3.04750856e+04 -3.32400304e+04 -2.23279836e+03  3.10686084e+03
  7.48130141e+03 -5.15899064e+03  1.68423123e+02 -4.91453226e+03
 -6.04276615e+03 -4.86665622e+03 -3.60087310e+03  0.00000000e+00
 -4.31272325e+04  3.10881415e+03 -6.89602852e+03 -4.84949433e+02
  1.31927978e+04  3.83228745e+04  2.67119971e+04  1.75695266e+04
 -3.92045565e+04  2.12473472e+01 -1.50431937e+04 -1.36587148e+04
  0.00000000e+00  0.00000000e+00 -2.99383020e+04 -3.59357457e+03
  1.39971868e+04  0.00000000e+00 -7.91514631e+03 -6.81073005e+04
 -2.84711183e+03 -3.61726597e+03 -1.11777262e+02 -1.49286789e+04
  1.86282671e+05 -3.60640247e+04 -1.94302213e+04 -1.36910454e+04
 -7.10417282e+04 -1.05963450e+04  0.00000000e+00  1.96360838e+04
  6.47822760e+03 -3.56524122e+03 -9.51552946e+02 -2.72371859e+04
 -1.21635833e+04  0.00000000e+00 -1.31531196e+03  1.09177226e+04
 -6.12622367e+02 -5.96170493e+03  2.96622067e+03 -3.19094968e+04
  3.56330055e+03  1.00009219e+03  1.98999936e+04  0.00000000e+00
  0.00000000e+00 -8.58717995e+03  2.62577118e+02 -2.43804091e+04
 -1.81099582e+04  0.00000000e+00  8.35198489e+02  0.00000000e+00
  1.32831124e+05 -7.00666826e+01  0.00000000e+00 -1.94060978e+03
 -3.75096134e+03 -4.84973140e+04  0.00000000e+00 -2.59467154e+04
 -6.16236655e+03  0.00000000e+00  1.22794547e+04  0.00000000e+00
 -7.83542173e+03 -6.32040658e+03 -6.41659466e+04 -1.04945096e+04
 -4.29853134e+04  3.43224606e+03 -2.61249560e+03 -1.11256036e+04
  0.00000000e+00  4.75344310e+03  7.01905376e+03 -1.24347789e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -8.40331484e+03  2.11363170e+04 -1.55600763e+04  2.17722886e+03
  4.60321868e+03 -1.77787995e+04  0.00000000e+00  9.24113687e+02
 -6.50821163e+03 -1.91332887e+04  7.42508429e+03 -3.15572645e+04
 -3.56877435e+04  1.54278124e+04  5.17280826e+03 -5.57293190e+04
 -4.96712585e+03 -1.38926859e+04 -7.01157436e+03 -7.16427113e+03
 -4.20619448e+04 -2.27799124e+03  1.62304010e+04 -6.86001326e+04
  1.74867017e+03  2.91372944e+03  0.00000000e+00  5.96593721e+02
  0.00000000e+00  1.02915262e+04  8.94648927e+02  3.78221144e+03
  1.79694087e+03  0.00000000e+00  0.00000000e+00  6.92878533e+02
 -7.38218014e+02 -2.61820725e+04  8.47340299e+04 -1.40592575e+05
  1.97196300e+04  8.96642822e+04  1.35298847e+05 -2.23140115e+05
 -1.54873317e+04  2.91069240e+05  2.71980412e+05 -1.56085090e+05
  4.55955082e+04 -2.14759241e+04  1.77226524e+04  1.41507277e+05
  5.38178647e+04 -7.06140170e+04  2.91690690e+04 -1.91252301e+05
  8.28869099e+04 -3.84222010e+04  8.81410168e+04  5.25049327e+04
 -3.59381730e+04  2.45058476e+04  9.57454427e+04 -1.43234647e+05
  1.55080789e+04  1.72415586e+04  1.12784268e+05  7.56654569e+03
 -3.89556409e+04 -6.65505510e+04  9.83820064e+04  2.75321451e+05
  9.09318616e+04 -1.27047994e+05 -1.79515940e+05  1.22969008e+05
 -2.13744271e+04]

3. Elastic Net Regression

In [64]:
from sklearn.linear_model import ElasticNet

In [69]:
el = ElasticNet(alpha = 1.0,l1_ratio=0.5)
el.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.878e+15, tolerance: 7.963e+11
  model = cd_fast.enet_coordinate_descent(

ElasticNet()

In [66]:
el.score(x_test,y_test)

0.10562833486018874

In [67]:
el.score(x_train,y_train)

0.0947567871157603